name: Compile & Prerelease Runix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      
      - name: Generate prerelease notes
        run: |
          echo '| :warning: WARNING                                        |' >> ReleaseNotes.md
          echo '|:--------------------------------------------------------:|' >> ReleaseNotes.md
          echo '| This project is incomplete and may not work as expected. |' >> ReleaseNotes.md
          git log -"1" --format="- %H %s" | sed '/^$/d' >> ReleaseNotes.md
      
      - name: Delete old prerelease
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: runix-unstable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish release
        uses: ncipollo/release-action@v1.8.10
        with:
          prerelease: true
          bodyFile: ReleaseNotes.md
          tag: "runix-unstable"
          token: ${{ secrets.GITHUB_TOKEN }}
  
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      
      - name: Build
        run: cargo build --release
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/runix.exe
          asset_name: runix-windows-x86_64.exe
          tag: "runix-unstable"
          overwrite: false
          prerelease: true
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      
      - name: Build
        run: cargo build --release
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/runix
          asset_name: runix-linux-x86_64
          tag: "runix-unstable"
          overwrite: false
          prerelease: true

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      
      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true
      
      - name: Build
        run: cargo build --release
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/runix
          asset_name: runix-macos-x86_64
          tag: "runix-unstable"
          overwrite: false
          prerelease: true